# Generated by Django 5.2.7 on 2025-10-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('difficulty', models.CharField(default='B', max_length=1)),
            ],
        ),
    ]
